# Tensorflow Operations

In TensorFlow, you collectively call constants, variables, operators as ops. TensorFlow is not just a
software library, but a suite of softwares that include TensorFlow, TensorBoard, and Tensor Serving.
To make the most out of TensorFlow, we should know how to use all of the above in conjunction
with one another. 

# Importing Libraries

In [1]:
import tensorflow as tf


# Tensorboard

When a user perform certain operations in a TensorBoard-activated TensorFlow program, these
operations are exported to an event log file. TensorBoard is able to convert these event files to
visualizations that can give insight into a model's graph and its runtime behavior. Learning to use
TensorBoard early and often will make working with TensorFlow much more enjoyable and
productive.

In [ ]:
a = tf.constant(2, name = "a")
b = tf.constant(3, name = "b")
x = tf.add(a, b, name = "add")

graph = tf.get_default_graph()
logdir = './graphs'
writer = tf.summary.FileWriter(logdir, graph)

with tf.Session() as sess:
    print (sess.run(x))
    
writer.close()

<h1> Visualizing with TensorBoard</h1>
To visualize the program with TensorBoard, we need to write log files of the program. In order to do so, we first need to create a writer for those logs with
<h4><center>writer = tf.summary.FileWriter([logdir], [graph])</center></h4>

- **[graph]** is the graph of the program you are working on. You can either call it using tf.get_default_graph(), which returns the default graph of the program, or through sess.graph, which returns the graph the session is handling. The latter requires you to already have created a session. Either way, make sure to create a writer only after you’ve defined your graph, else the graph visualized on TensorBoard would be incomplete.

- **[logdir]** is the folder where you want to store those log files. You can choose [logdir] to be something meaningful such as './graphs'.

In [ ]:
a = tf.constant(2)
b = tf.constant(3)
x = tf.add(a, b)
writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
with tf.Session() as sess:
    # writer = tf.summary.FileWriter('./graphs', sess.graph) # if you prefer creating
    # your writer using session's graph
    print(sess.run(x))
writer.close()

Next, go to Terminal, run the program. Make sure that your present working directory is the same as
where you ran your Python code.

\$ python3 [filename.py] <br>
\$ tensorboard --logdir="./graphs" --port 6006

Open your browser and go to http://localhost:6006/ (or the port of your choice), you will see the
TensorBoard page. Go to the Graph tab and you can verify that the graph indeed has 3 nodes, two
constants and an Add op.

# Constants

You can create a tensor of a specific dimension and fill it with a specific value, similar to Numpy

In [2]:
# constant of 2x2 tensor (matrix)
b = tf.constant([[0, 1], [2, 3]], name="matrix")
with tf.Session() as sess:
    print (sess.run(b))

[[0 1]
 [2 3]]


In [3]:
# tf.zeros(shape, dtype = tf.float32, name = None)
# create a tensor of shape and all elements are zeros
b = tf.zeros([2, 3], tf.int32) # ==> [[0, 0, 0], [0, 0, 0]]
with tf.Session() as sess:
    print (sess.run(b))

[[0 0 0]
 [0 0 0]]


In [4]:
# tf.ones(shape, dtype = tf.float32, name = None)
# create a tensor of shape and all elements are zeros
b = tf.ones([2, 3], tf.int32) # ==> [[0, 0, 0], [0, 0, 0]]
with tf.Session() as sess:
    print (sess.run(b))

[[1 1 1]
 [1 1 1]]


In [6]:
#tf.fill(dims, value, name = None)
# create a tensor filled with a scalar value.
b = tf.fill(dims = [2, 3],value = 8) 
with tf.Session() as sess:
    print (sess.run(b))

[[8 8 8]
 [8 8 8]]


Creating constant as sequence

In [7]:
#tf.lin_space(start, stop, num, name = None)
# create a sequence of num evenly-spaced values are generated beginning at start. If num >
# 1, the values in the sequence increase by (stop - start) / (num - 1), so that the last one
# is exactly stop.
# comparable to but slightly different from numpy.linspace
b = tf.lin_space(start = 10.0, stop = 13.0, num = 4, name="linspace") 
with tf.Session() as sess:
    print (sess.run(b))

[10. 11. 12. 13.]


<b> Unlinke numpy sequences, tensorflow sequences are not iterable </b>

In [8]:
for i in tf.linspace(0.0, 10.0, 4):
    print (i)

TypeError: Tensor objects are not iterable when eager execution is not enabled. To iterate over this tensor use tf.map_fn.

# Math Operations
Tensorflow maths operations are pretty standard, except for division operations. There are half a duzen types of divisions in tensorflow, so keep in mind to read each one's documentation before using it, but here are a couple of examples. 

In [10]:
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')

with tf.Session() as sess:    
    print(sess.run(tf.div(b, a))) 
    print(sess.run(tf.divide(b, a))) 
    print(sess.run(tf.truediv(b, a))) 
    print(sess.run(tf.floordiv(b, a))) 
    #print(sess.run(tf.realdiv(b, a))) # ⇒ Error: only works for real values
    print(sess.run(tf.truncatediv(b, a))) # ⇒ [[0 0] [1 1]]
    print(sess.run(tf.floor_div(b, a))) # ⇒ [[0 0] [1 1]]

[[0 0]
 [1 1]]
[[0.  0.5]
 [1.  1.5]]
[[0.  0.5]
 [1.  1.5]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]


## Adding Tensors

In [12]:
a = tf.constant([[2, 2], 
                 [1, 1]], name='a')
b = tf.constant([[0, 1], 
                 [2, 3]], name='b')
x = tf.add_n([a, b], name = 'add') # => equivalent to a + b + b
with tf.Session() as sess:    
    print (sess.run(x))

[[2 3]
 [3 4]]


## Dot Product

In [16]:
a = tf.constant([[8, 2], 
                 [4, 2]], name='a')
b = tf.constant([[1, -1], 
                 [-2, 4]], name='b')
with tf.Session() as sess:
    print(sess.run(tf.multiply(a, b))) # ⇒ [20 60] # element-wise multiplication
    print(sess.run(tf.tensordot(a, b, 1))) # ⇒ 80 # multiplies matrices of ranks greater or equal to 2.

[[ 8 -2]
 [-8  8]]
[[4 0]
 [0 4]]


# Variables
Constants have been fun and now is the time to learn about what really matters: variables. The
differences between a constant and a variable:
- A constant is, well, constant. Often, you’d want your weights and biases to be updated during
training.
- A constant's value is stored in the graph and replicated wherever the graph is loaded. A variable
is stored separately, and may live on a parameter server.

The second point means that constants are stored in the graph definition. When constants are memory
expensive, such as a weight matrix with millions of entries, it will be slow each time you have to load
the graph. To see what’s stored in the graph's definition, simply print out the graph's protobuf.
Protobuf stands for protocol buffer, “Google's language-neutral, platform-neutral, extensible
mechanism for serializing structured data – think XML, but smaller, faster, and simpler .”
3

In [20]:
# Cleaning Graph
tf.reset_default_graph()
my_const = tf.constant([1.0, 2.0], name="my_const")
print(tf.get_default_graph().as_graph_def())

node {
  name: "my_const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\000\000\200?\000\000\000@"
      }
    }
  }
}
versions {
  producer: 26
}



## Initializing Variables
TensorFlow recommends that we use the wrapper
tf.get_variable, which allows for easy variable sharing. With tf.get_variable, we can provide variable’s
internal name, shape, type, and initializer to give the variable its initial value. Note that when we use
tf.constant as an initializer, we don’t need to provide shape.

In [23]:
tf.reset_default_graph()
s = tf.get_variable("scalar", initializer=tf.constant(2))
m = tf.get_variable("matrix", initializer=tf.constant([[0, 1], [2, 3]]))
W = tf.get_variable("big_matrix", shape=(784, 10), initializer=tf.zeros_initializer())
u = tf.get_variable("unused_variable", shape=(784, 10))

You have to initialize a variable before using it. If you try to evaluate the variables before initializing
them you'll run into FailedPreconditionError: Attempting to use uninitialized value. To get a list of
uninitialized variables, you can just print them out:

In [27]:
with tf.Session() as sess:
    # To get uninitialized variables:
    print(sess.run(tf.report_uninitialized_variables()))
    
    # The easiest way to initialize all variables is: 
    sess.run(tf.global_variables_initializer())
        
    print(sess.run(tf.report_uninitialized_variables()))
    
    

['scalar' 'matrix' 'big_matrix' 'unused_variable']
[]


You can also initialize each variable separately using tf.Variable.initializer

In [31]:
with tf.Session() as sess:
    print(sess.run(tf.report_uninitialized_variables()))
    sess.run(W.initializer)
    print(sess.run(tf.report_uninitialized_variables()))

['scalar' 'matrix' 'big_matrix' 'unused_variable']
['scalar' 'matrix' 'unused_variable']


## Assigning Values to Variables

In [52]:
tf.reset_default_graph()

W = tf.get_variable("scalar", initializer=tf.constant(10))
with tf.Session() as sess:    
    sess.run(tf.global_variables_initializer())
    print (sess.run(W))

# Assigning new value
assign_op = W.assign(100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())    
    sess.run(W)
    print(W.eval()) # >> 10

10
10


As we can see in the cell above, we tried to assign '100' to the W variable by using **W.assign(100)**, but it had no effect. This is because the **assign** method is also an operation, so it has to be run in the session

In [53]:
tf.reset_default_graph()
W = tf.get_variable("scalar", initializer=tf.constant(10))
with tf.Session() as sess:    
    sess.run(tf.global_variables_initializer())
    print (sess.run(W))

assign_op = W.assign(100)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    # Running assign operation
    sess.run(assign_op)
    sess.run(W)
    print(W.eval()) # >> 100

10
100


For simple incrementing/decrementing of variables, Tensorflow includes:
- tf.Variable.assign_add()
- tf.Variable.assign_sub() 

Unlike tf.Variable.assign(), tf.Variable.assign_add() and tf.Variable.assign_sub() don't initialize your variables for you because these ops depend on the initial values of the variable.

In [58]:
tf.reset_default_graph()
W = tf.Variable(10)
with tf.Session() as sess:
    sess.run(W.initializer)
    print(sess.run(W.assign_add(10))) # >> 20
    print(sess.run(W.assign_sub(2))) # >> 18

20
18


When you have a variable that depends on another variable, suppose you want to declare U = W * 2

In [67]:
tf.reset_default_graph()
# W is a random 700 x 10 tensor
W = tf.Variable(tf.ones([2, 3]))
U = tf.Variable(W * 2)

In this case, you should use **initialized_value()** to make sure that W is initialized before its value is used to initialize U.

In [68]:
U = tf.Variable(W.initialized_value() * 2)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(W)) # >> 20
    print(sess.run(U)) # >> 18

[[1. 1. 1.]
 [1. 1. 1.]]
[[2. 2. 2.]
 [2. 2. 2.]]


# Importing Data
Remember that a TensorFlow program often has 2 phases:

- Phase 1: assemble a graph
- Phase 2: use a session to execute operations and evaluate variables in the graph

We can assemble the graphs first without knowing the values needed for computation. This is
equivalent to defining the function of x, y without knowing the values of x, y. For example:

<h4><center>f(x, y) = 2x + y</h4></center>

x, y are **placeholders** for the actual values. <br>
With the graph assembled, we, or our clients, can later supply their own data when they need to
execute the computation. To define a placeholder, we use:

<h4><center>tf.placeholder(dtype, shape=None, name=None)</h4></center>

Dtype, shape, and name are self-explanatory. The only thing to note here is when you set the shape of
the placeholder to None. **shape=None means that tensors of any shape will be accepted**. Using
shape=None is easy to construct graphs, but nightmarish for debugging. **You should always define the
shape of your placeholders as detailed as possible**. shape=None also breaks all following shape inference,
which makes many ops not work because they expect certain rank.

In [72]:
tf.reset_default_graph()
x = tf.placeholder(tf.float32, shape=[3]) # a is placeholder for a vector of 3 elements
b = tf.constant([5, 5, 5], tf.float32)

In [73]:
y = 2*x + b # use the placeholder as you would any tensor
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(y, {x: [1, 2, 3]}))

[ 7.  9. 11.]


We can feed as many data points to the placeholder as we want by iterating through the data set and
feed in the value one at a time.



In [74]:
# with tf.Session() as sess:
#    for a_value in list_of_a_values:
#        print(sess.run(c, {a: a_value}))               

You can feed values to tensors that aren't placeholders. Any tensors that are feedable can be fed. To
check if a tensor is feedable or not, use: 

<h4><center>tf.Graph.is_feedable(tensor)</center></h4>

In [77]:
a = tf.add(2, 5)
b = tf.multiply(a, 3)
with tf.Session() as sess:
    print(sess.run(b)) # >> 7*3 = 21
    # compute the value of b given the value of a is 15*3 = 15
    print(sess.run(b, feed_dict={a: 15})) 

21
45
